### ISSUE TITLE
When the frost, the suspension begins chaos

### ISSUE THREAD

**Issue by whakru** [olliw42/storm32bgc#13]
When I start to use the suspension when the frost is at -5 and below (I leave the house to the street). After some time (1-5 minutes) the suspension starts to throw in different directions, chaos begins. But after rebooting everything comes back to normal. Sensor used on I2C error 0.
If the suspension is frozen for 5-10 minutes on the street, then the mayhem does not occur
....
Когда я начинаю использовать подвес при морозе в -5 и ниже (выхожу из дома на улицу). То через какое то время (1-5 минут) подвес начинает кидать в разные стороны, начинается беспредел. Но после перезагрузки все приходит в норму. Используется датчик на I2C ошибок 0.
Если подвес проморозить минут 5-10 на улице то беспредела  не просиходит

**Comment by olliw42** [comment]
shouldn't happen really
try leaving the gimbal outside for some 10 minutes and 5then restart
outdated
