### ISSUE TITLE
IMU not available

### ISSUE THREAD

**Issue by Vishranthee** [olliw42/storm32bgc#15]
I tried my level best and went through all the RC group pages and re-flashed the firmware multiple times. But IMU is not available and I'm unable to calibrate it by any means.

Power LED is solid.  @olliw42 

![IMU](https://user-images.githubusercontent.com/32018358/71969711-3c037c80-322d-11ea-812e-ce0513e3a91a.jpg)

**Comment by olliw42** [comment]
you probably have a I2C-based IMU and not an NT IMU, ie., use the wrong firmware. Please read up in the wiki: http://www.olliw.eu/storm32bgc-wiki/Downloads

the primary location for questions & discussions is btw here: https://www.rcgroups.com/forums/showthread.php?2055844-STorM32-BGC-32-bit-3-axis-brushless-gimbal-controller

**Comment by olliw42** [comment]
no further response so seems to be resolved and I close :)
