### ISSUE TITLE
Question: Can you use the storm 32 as a driver

### ISSUE THREAD

**Issue by finnBsch** [olliw42/storm32bgc#16]
Hi,
I am desperately looking for a way to drive gimbal motors with an arduino.  I don't use the gimbal motors in a gimbal, so the storm32 board isn't helping.  However since it has the capability to drive these motors, maybe there's a way to use it to speed controll the motors based on arduino input? No stabilization whatsoever is  needed though..

**Comment by olliw42** [comment]
I can do that using what it calls the "servo" mode

by principle, without encoders, the rotation is however not very "smooth" (issue is motor cogging)

I think this answers this, so I'm closing. If you have more questions on this, please reopen, or even better, join the rcgroups discussion thread :)
