### ISSUE TITLE
STorM32 BGC board v1.10

### ISSUE THREAD

**Issue by olliw42** [olliw42/storm32bgc#2]
This board does work perfectly, it hasn't any electrical issues.

However, it has some minor mistakes/imperfections:
- the labelling of the SWD port is incorrect, it should be SWDIO,GND,SWCLK,3.3V (instead of GND,SWCLK,SWDIO,3.3V)
- the two big solder holes for the battery cable are missing solder rings on the bottom
- the sequence of pins of the I2C#2 port is reverse as compared to that of the MPU I2C port (hence, and IMU module connected the MPU port MUST NOT be connecetd to the I2C#2 port, and vice versa)

Obviously, these points will be taken care in the next release.

**Comment by CradyCopter** [comment]
Hi Olli,

I have a new v1.1 board that arrived without firmware installed from Witespy.

I was able to successfully flash the firmware several times but after every flashing I Windows 7 never assigns a COM port to the board and the GUI can't see it.

Tried several re-flashes, power cycling, different cables, etc. but regardless of which USB port I try on my computer Windows never sees board.

**Comment by olliw42** [comment]
board is deprecated
