### ISSUE TITLE
unable to calibrate "imu1 is not present or on healty!"

### ISSUE THREAD

**Issue by onlineapps-cloud** [olliw42/storm32bgc#24]
hi, i tried to calibrate my gimbal, i have installed imu2, and he working as expected, but when i want to calibrate i cannot bypasss this erro, in wizard i disabled imu1 check, but not help :(
can anyone say, what i do wrong?
![image](https://github.com/olliw42/storm32bgc/assets/69077240/e1183af7-ab7d-4a40-88f3-ba796f412170)
![image](https://github.com/olliw42/storm32bgc/assets/69077240/bbd990bd-150f-48e8-a07b-9a642bbcb5ee)
![image](https://github.com/olliw42/storm32bgc/assets/69077240/944bb33e-2546-4733-862f-22457037b317)
![image](https://github.com/olliw42/storm32bgc/assets/69077240/69aba70b-8587-4665-bffc-e59dc8744463)

**Comment by onlineapps-cloud** [comment]
in wiki http://www.olliw.eu/storm32bgc-wiki/Using_a_2nd_IMU
The calibration of the 2nd IMU works similar to the camera IMU; one just has to select the 2nd IMU in the respective fields. 
but, this not work, i had errol that "imu1 is not present or on healty!"

**Comment by onlineapps-cloud** [comment]
![image](https://github.com/olliw42/storm32bgc/assets/69077240/d7d99cba-0499-45fe-b507-bd9a9816cb48)

**Comment by onlineapps-cloud** [comment]
![image](https://github.com/olliw42/storm32bgc/assets/69077240/e70ea768-6e17-4b7a-bc63-e7c619785852)

**Comment by onlineapps-cloud** [comment]
sorry, im newbie, i have only gimbal, i need additional camera with IMU? can you give some example?
![image](https://github.com/olliw42/storm32bgc/assets/69077240/9635cf26-7e75-4dde-b1fc-35eac7119b14)

**Comment by onlineapps-cloud** [comment]
as i understand this sensor not workin, yes? IMU2 is accelerometer that is onboard, yes?

**Comment by olliw42** [comment]
pl go first to the wiki, it will answer nearly all your questions ... you are expected to have spend sufficient time with the wiki, otherwise you will not get to anywhere with STorM32.

Read espeically also big red warning boxes, like this one here: http://www.olliw.eu/storm32bgc-wiki/Downloads

**Comment by onlineapps-cloud** [comment]
i searched my IMU module, but i cannot find it here http://www.olliw.eu/storm32bgc-wiki/Overview_of_NT_Modules
my IMU module is not listed,
module close view. Model: INVENSENSE MPU-6050
![1PXL_20230914_190415559_1](https://github.com/olliw42/storm32bgc/assets/69077240/f91bf9f9-37b2-442e-bc0d-c3813af3c106)

Ensys NT Modules uses MPU-6050, which firmware i need to load, to work this IMU module?
![image](https://github.com/olliw42/storm32bgc/assets/69077240/f1f72ad1-d302-4d66-9eb0-6e0cd044a3e2)

**Comment by onlineapps-cloud** [comment]
Also i want donate (if you accept donations) for future development (and for your great work!), i can pay in crypto only.

**Comment by onlineapps-cloud** [comment]
![image](https://github.com/olliw42/storm32bgc/assets/69077240/972cedc8-fc74-4e53-9be7-9baabfd1f6c7)
now i understand why it will not work, i need firmware that will support this IMU device, yes? if yes, i don't know which firmware support this IMU module :(, i still reading  documentation :)

**Comment by onlineapps-cloud** [comment]
yes, you are correct, firmware work as expected, my apologies!
