### ISSUE TITLE
STorm32 GIMBAL CONTROLLER 

### ISSUE THREAD

**Issue by shivamydv2001** [olliw42/storm32bgc#25]
Hi everyone, I want to control  STorM32 gimbal controller uisng mavlink . 
board v1.32
f.v.--0.90 
So can anyone guide me to solve .

**Comment by olliw42** [comment]
please read the documentation!
we are not here to do the basic google for you!
anyway: http://www.olliw.eu/storm32bgc-v1-wiki/Main_Page
