### ISSUE TITLE
CMD_GETDATAFIELDS result does not match documentation

### ISSUE THREAD

**Issue by vryabokon1705** [olliw42/storm32bgc#27]
Version: v2.67e ll, OlliW 323BGC, v3.3 F103RC
https://www.olliw.eu/storm32bgc-wiki/Serial_Communication
Looks like CMD_GETDATAFIELDS serial command documentation is inaccurate. For example, if i use 0x0020 = LIVEDATA_IMU1ANGLES, i receive the same data as in Imu1AHRS.R.x, Imu1AHRS.R.y, Imu1AHRS.R.z from command CMD_GETDATA, and if i use 0x0010 = LIVEDATA_IMU1R, i receive the same data as in aImu1Angle.Pitch, aImu1Angle.Roll, aImu1Angle.Yaw 
Plus if i want to use 0x0004 = LIVEDATA_IMU1GYRO and 0x0008 = LIVEDATA_IMU1ACC, i cannot find documentation how can i decode these data, CMD_GETDATA comman does not include LIVEDATA_IMU1GYRO and LIVEDATA_IMU1ACC

**Comment by olliw42** [comment]
hey @vryabokon1705 
many thx for the report, it's possible that the docs doesn't match, I haven't looked at it for some while. I will look into it.
can I ask: if you use CMD_GETDATA and the simple 'd' command, you do get the same data, and these data match the description for the 'd' command, right?

**Comment by vryabokon1705** [comment]
Hi. I did not use d command yet, but CMD_GETDATA result looks like match description of data from 'd' command

**Comment by olliw42** [comment]
ok, thanks.
I will look into it.
