### ISSUE TITLE
NT logging bitmask include basic automatically

### ISSUE THREAD

**Issue by sheldonHe1996** [olliw42/storm32bgc#30]
Hello, olliw;
   when i set nt logging bitmask only to include pid in option, it seems the basic logging data is also chosed.

**Comment by olliw42** [comment]
there must be a minimum set of default logging data for the logging to work at all

pl note that the github issues are not for support questions, there is the rcgroups thread for that 

closing since I believe no issue and question is answered. Thx for the comment.
