### ISSUE TITLE
 downgrading to a single-axis gimbal

### ISSUE THREAD

**Issue by Shen-LW** [olliw42/storm32bgc#32]
I want to fix the roll and yaw, stabilizing only the pitch, similar to downgrading to a single-axis gimbal. What modifications do I need to make?

**Comment by olliw42** [comment]
this github repository is NOT for support questions. Pl choose the rcgroups discussion thread.

hint: there is also a wiki, and reading it can be very benefitial.

closing since no issue but support.

**Comment by Shen-LW** [comment]
> this github repository is NOT for support questions. Pl choose the rcgroups discussion thread.
> 
> hint: there is also a wiki, and reading it can be very benefitial.
> 
> closing since no issue but support.

Thank you for your reply. I understand now.
