### ISSUE TITLE
Can't connect to gimbal - "Read...Aborted!"

### ISSUE THREAD

**Issue by chicco4life** [olliw42/storm32bgc#4]
Hi, 

I just purchased a GoodluckBuy gimbal with the v1.31 Storm32 board.  I have installed the driver for my ttl-usb converter and plugged it in.  I was able to open up the V0.8 GUI and flash its firmware - yet after firmware flashing is successful, I can't seem to boot up the gimbal from my computer.  It says Read...Aborted, and asks me to read first.  Yet when I press read, it gives me the same error message.  Could you please help?

**Comment by olliw42** [comment]
outdated
