### ISSUE TITLE
Is firmware OpenSource

### ISSUE THREAD

**Issue by Tommixoft** [olliw42/storm32bgc#6]
Hi i guess this is stupid question - but does firmware source is open source? or GUI app?
I guess not yes? :)

**Comment by Tommixoft** [comment]
PS ohh...so this file "o323BGCTool_v096.pl" is the source? :) Wow..perl on windows..first time see that :)

Would be great to make GUI using .net (best java to use on all platforms..but i hate java i love .net :D )

**Comment by sorki** [comment]
I'll add this for reference:

The hardware is open source, the firmware is free.
(rcgroups post)

**Comment by Tommixoft** [comment]
in other words future of this is in one man hands, that why it have no future.

**Comment by olliw42** [comment]
correct, there is no future for human kind without open source
