### ISSUE TITLE
MOST usful feature suggestion

### ISSUE THREAD

**Issue by Tommixoft** [olliw42/storm32bgc#7]
Hi, yesterday i though of super feature to add to board - current draw info. SO people can see in "real time" how much current is drawn so by this we can know how good we balanced gimbal, If you dont have ability to add amps - you maybe can think something by using info you sending to motor controllers. SO if there is high amount of correction sent -this means bad calibration (of course if gimbal is in steady position).
I think such feature would be great.

**Comment by Tommixoft** [comment]
sad this is dead project.

**Comment by noradtux** [comment]
Try to contact olliw on rcgroups.com. This project is far from dead, but it's not using github as it's primary development plattform.

**Comment by Tommixoft** [comment]
@noradtux RC groups is filled with noob questions and in 1 hour my suggestion would be 5 pages behind :) So i put here. What do you think about my feature? Would it be useful to you?

**Comment by noradtux** [comment]
@Tommixoft I think using the NT-logger provides better means of evaluating how well the system is balanced. So no, I wouldn't consider measuring current draw to have any benefit over what is already there.

**Comment by Tommixoft** [comment]
NT logger works with NON nt firmware? Cause all that nt stuff is overrated. i in my entire using never got even single I2C error.

**Comment by noradtux** [comment]
Well, development of non-NT-stuff has effectively halted. NT isn't just about better rejection of interference, it also gives benefits like the nt-logger and camera modules, giving me more functionality with less wires. I could even reduce wires more if I used the motor modules.

**Comment by Tommixoft** [comment]
Hmmm camera modules? what is this? Maybe i will buy NT sensor some day, my country makes them, anyways, im using this board as gimbal for camera, not on drone, so so far it provides all needed functions, but i wish firmware be open source, now everything depends on 1 person.

**Comment by noradtux** [comment]
I use a cc3d atom as camera-IMU. I can use two of its servo outputs to control the camera. I think you will find the wiki enlightening.

**Comment by olliw42** [comment]
the hardware can't do current measuerment
outdated
